#!/usr/bin/env python3
import json
import os

# Define the notebook structure
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["# Hyperliquid Whale Position Analysis\n", "\n", "This notebook provides interactive analysis of whale positions on Hyperliquid."]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import plotly.express as px\n",
                "import plotly.graph_objects as go\n",
                "import os\n",
                "from IPython.display import display, HTML\n",
                "\n",
                "# Set visualization style\n",
                "plt.style.use('ggplot')\n",
                "sns.set_palette(\"viridis\")\n",
                "plt.rcParams['figure.figsize'] = (12, 8)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Load the data\n",
                "DATA_DIR = \"bots/hyperliquid/data/ppls_positions\"\n",
                "positions_file = os.path.join(DATA_DIR, \"all_positions.csv\")\n",
                "agg_file = os.path.join(DATA_DIR, \"aggregated_positions.csv\")\n",
                "\n",
                "# Check if files exist\n",
                "if not os.path.exists(positions_file) or not os.path.exists(agg_file):\n",
                "    print(\"⚠️ Data files not found. Please run positions.py first to generate the data files.\")\n",
                "else:\n",
                "    # Load the data\n",
                "    positions_df = pd.read_csv(positions_file)\n",
                "    agg_df = pd.read_csv(agg_file)\n",
                "    \n",
                "    print(f\"✅ Loaded {len(positions_df)} positions from {positions_df['address'].nunique()} unique addresses\")\n",
                "    \n",
                "    # Display basic statistics\n",
                "    total_value = positions_df['position_value'].sum()\n",
                "    print(f\"📊 Total position value: ${total_value:,.0f}\")\n",
                "    print(f\"🪙 Number of coins: {positions_df['coin'].nunique()}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 1. Overview of Position Distribution"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Distribution of positions by coin\n",
                "coin_dist = positions_df.groupby('coin')['position_value'].sum().sort_values(ascending=False).reset_index()\n",
                "\n",
                "# Create a pie chart\n",
                "fig = px.pie(coin_dist, values='position_value', names='coin', \n",
                "             title='Position Distribution by Coin',\n",
                "             hover_data=['position_value'], labels={'position_value':'Position Value ($)'})\n",
                "fig.update_traces(textposition='inside', textinfo='percent+label')\n",
                "fig.update_layout(uniformtext_minsize=12, uniformtext_mode='hide')\n",
                "fig.show()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Position value by long vs short\n",
                "direction_value = positions_df.groupby(['is_long', 'coin'])['position_value'].sum().reset_index()\n",
                "direction_value['direction'] = direction_value['is_long'].map({True: 'Long 📈', False: 'Short 📉'})\n",
                "\n",
                "# Sort by total position value\n",
                "coin_order = positions_df.groupby('coin')['position_value'].sum().sort_values(ascending=False).index.tolist()\n",
                "direction_value['coin'] = pd.Categorical(direction_value['coin'], categories=coin_order, ordered=True)\n",
                "direction_value = direction_value.sort_values('coin')\n",
                "\n",
                "# Create a grouped bar chart\n",
                "fig = px.bar(direction_value, x='coin', y='position_value', color='direction',\n",
                "             title='Long vs Short Positions by Coin',\n",
                "             labels={'position_value': 'Position Value ($)', 'coin': 'Coin'},\n",
                "             color_discrete_map={\"Long 📈\": \"green\", \"Short 📉\": \"red\"},\n",
                "             barmode='group')\n",
                "fig.update_layout(xaxis_title='Coin', yaxis_title='Position Value ($)')\n",
                "fig.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 2. Top Whale Analysis"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Identify top whales by total position value\n",
                "top_whales = positions_df.groupby('address')['position_value'].sum().sort_values(ascending=False).head(20)\n",
                "\n",
                "# Format the whale addresses for better display\n",
                "top_whales = top_whales.reset_index()\n",
                "top_whales['short_address'] = top_whales['address'].apply(lambda x: f\"{x[:6]}...{x[-4:]}\")\n",
                "\n",
                "# Plot top whales\n",
                "fig = px.bar(top_whales, x='short_address', y='position_value',\n",
                "             title='Top 20 Whales by Total Position Value',\n",
                "             labels={'position_value': 'Total Position Value ($)', 'short_address': 'Wallet Address'})\n",
                "fig.update_layout(xaxis_title='Wallet Address', yaxis_title='Total Position Value ($)')\n",
                "fig.show()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Analyzing position diversity of top whales\n",
                "def analyze_whale(address):\n",
                "    \"\"\"Analyze a specific whale's positions\"\"\"\n",
                "    whale_data = positions_df[positions_df['address'] == address]\n",
                "    \n",
                "    if whale_data.empty:\n",
                "        return \"No data found for this address\"\n",
                "    \n",
                "    # Show summary statistics\n",
                "    total_value = whale_data['position_value'].sum()\n",
                "    print(f\"Whale: {address[:6]}...{address[-4:]}\")\n",
                "    print(f\"Total Position Value: ${total_value:,.0f}\")\n",
                "    print(f\"Number of Positions: {len(whale_data)}\")\n",
                "    print(f\"Number of Coins: {whale_data['coin'].nunique()}\")\n",
                "    \n",
                "    # Long vs Short bias\n",
                "    long_value = whale_data[whale_data['is_long']]['position_value'].sum()\n",
                "    short_value = whale_data[~whale_data['is_long']]['position_value'].sum()\n",
                "    long_pct = long_value / total_value * 100 if total_value > 0 else 0\n",
                "    short_pct = short_value / total_value * 100 if total_value > 0 else 0\n",
                "    print(f\"Long Positions: ${long_value:,.0f} ({long_pct:.1f}%)\")\n",
                "    print(f\"Short Positions: ${short_value:,.0f} ({short_pct:.1f}%)\")\n",
                "    \n",
                "    # Create a pie chart of the whale's positions by coin\n",
                "    coin_dist = whale_data.groupby('coin')['position_value'].sum().reset_index()\n",
                "    fig = px.pie(coin_dist, values='position_value', names='coin',\n",
                "                title=f\"Portfolio Composition for {address[:6]}...{address[-4:]}\",\n",
                "                hover_data=['position_value'], labels={'position_value': 'Position Value ($)'})\n",
                "    fig.update_traces(textposition='inside', textinfo='percent+label')\n",
                "    fig.show()\n",
                "    \n",
                "    # Return the whale's positions sorted by value\n",
                "    return whale_data.sort_values('position_value', ascending=False)[['coin', 'position_value', 'is_long', 'entry_price', 'liquidation_price', 'unrealized_pnl']]\n",
                "\n",
                "# Analyze the top whale\n",
                "if not top_whales.empty:\n",
                "    top_whale_address = top_whales.iloc[0]['address']\n",
                "    top_whale_positions = analyze_whale(top_whale_address)\n",
                "    display(top_whale_positions.style.format({\n",
                "        'position_value': '${:,.0f}',\n",
                "        'entry_price': '${:.2f}',\n",
                "        'liquidation_price': '${:.2f}',\n",
                "        'unrealized_pnl': '${:,.0f}'\n",
                "    }))"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 3. Market Sentiment Analysis"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Calculate market sentiment for each coin\n",
                "sentiment_data = []\n",
                "\n",
                "for coin in positions_df['coin'].unique():\n",
                "    coin_data = positions_df[positions_df['coin'] == coin]\n",
                "    \n",
                "    # Skip if no data\n",
                "    if coin_data.empty:\n",
                "        continue\n",
                "        \n",
                "    long_value = coin_data[coin_data['is_long']]['position_value'].sum()\n",
                "    short_value = coin_data[~coin_data['is_long']]['position_value'].sum()\n",
                "    total_value = long_value + short_value\n",
                "    \n",
                "    # Skip if no positions\n",
                "    if total_value == 0:\n",
                "        continue\n",
                "        \n",
                "    # Calculate sentiment (-1 to 1 scale)\n",
                "    sentiment = (long_value - short_value) / total_value\n",
                "    \n",
                "    sentiment_data.append({\n",
                "        'coin': coin,\n",
                "        'sentiment': sentiment,\n",
                "        'long_value': long_value,\n",
                "        'short_value': short_value,\n",
                "        'total_value': total_value,\n",
                "        'whale_count': coin_data['address'].nunique()\n",
                "    })\n",
                "\n",
                "# Convert to DataFrame\n",
                "sentiment_df = pd.DataFrame(sentiment_data)\n",
                "\n",
                "if not sentiment_df.empty:\n",
                "    # Sort by total value\n",
                "    sentiment_df = sentiment_df.sort_values('total_value', ascending=False)\n",
                "    \n",
                "    # Plot sentiment by coin (top coins by value)\n",
                "    top_coins = sentiment_df.head(10)\n",
                "    fig = px.bar(top_coins, x='coin', y='sentiment',\n",
                "                title='Market Sentiment by Top Coins (By Volume)',\n",
                "                labels={'sentiment': 'Sentiment (-1 = Bearish, 1 = Bullish)', 'coin': 'Coin'},\n",
                "                color='sentiment',\n",
                "                color_continuous_scale=['red', 'lightgray', 'green'],\n",
                "                range_color=[-1, 1])\n",
                "    fig.update_layout(xaxis_title='Coin', yaxis_title='Sentiment')\n",
                "    fig.add_shape(type='line', x0=-0.5, x1=len(top_coins)-0.5, y0=0, y1=0,\n",
                "                  line=dict(color='black', width=2, dash='solid'))\n",
                "    fig.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 4. Whale Clustering Analysis"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Group whales by their trading patterns\n",
                "from sklearn.cluster import KMeans\n",
                "from sklearn.preprocessing import StandardScaler\n",
                "\n",
                "# Focus on whales with at least 3 positions\n",
                "whale_counts = positions_df['address'].value_counts()\n",
                "active_whales = whale_counts[whale_counts >= 3].index.tolist()\n",
                "\n",
                "# Create a features matrix for clustering\n",
                "coins = positions_df['coin'].unique()\n",
                "whale_features = []\n",
                "\n",
                "for whale in active_whales:\n",
                "    whale_data = positions_df[positions_df['address'] == whale]\n",
                "    \n",
                "    # Skip if no data\n",
                "    if whale_data.empty:\n",
                "        continue\n",
                "        \n",
                "    # Total position value\n",
                "    total_value = whale_data['position_value'].sum()\n",
                "    \n",
                "    # Long bias\n",
                "    long_value = whale_data[whale_data['is_long']]['position_value'].sum()\n",
                "    long_bias = long_value / total_value if total_value > 0 else 0\n",
                "    \n",
                "    # Create a feature vector with allocation by coin\n",
                "    features = {'address': whale, 'total_value': total_value, 'long_bias': long_bias}\n",
                "    \n",
                "    for coin in coins:\n",
                "        coin_value = whale_data[whale_data['coin'] == coin]['position_value'].sum()\n",
                "        features[f'pct_{coin}'] = coin_value / total_value if total_value > 0 else 0\n",
                "    \n",
                "    whale_features.append(features)\n",
                "\n",
                "# Convert to DataFrame\n",
                "features_df = pd.DataFrame(whale_features)\n",
                "\n",
                "# Skip the clustering if we don't have enough data\n",
                "if len(features_df) < 5:\n",
                "    print(\"Not enough whale data to perform clustering.\")\n",
                "else:\n",
                "    # Prepare feature matrix (exclude address and total_value columns)\n",
                "    X_cols = [col for col in features_df.columns if col not in ['address', 'total_value']]\n",
                "    X = features_df[X_cols].values\n",
                "    \n",
                "    # Scale features\n",
                "    scaler = StandardScaler()\n",
                "    X_scaled = scaler.fit_transform(X)\n",
                "    \n",
                "    # Determine optimal number of clusters\n",
                "    from sklearn.metrics import silhouette_score\n",
                "    \n",
                "    sil_scores = []\n",
                "    K = range(2, min(10, len(features_df) // 3))\n",
                "    \n",
                "    for k in K:\n",
                "        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)\n",
                "        labels = kmeans.fit_predict(X_scaled)\n",
                "        sil_scores.append(silhouette_score(X_scaled, labels))\n",
                "    \n",
                "    # Choose optimal number of clusters\n",
                "    best_k = K[np.argmax(sil_scores)]\n",
                "    \n",
                "    # Apply final clustering\n",
                "    kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)\n",
                "    features_df['cluster'] = kmeans.fit_predict(X_scaled)\n",
                "    \n",
                "    # Plot silhouette scores\n",
                "    plt.figure(figsize=(10, 6))\n",
                "    plt.plot(K, sil_scores, 'bo-')\n",
                "    plt.xlabel('Number of Clusters')\n",
                "    plt.ylabel('Silhouette Score')\n",
                "    plt.title('Optimal Number of Whale Clusters')\n",
                "    plt.grid(True)\n",
                "    plt.show()\n",
                "    \n",
                "    # Visualize clusters\n",
                "    print(f\"Identified {best_k} clusters of whale trading strategies\")\n",
                "    \n",
                "    # For each cluster, show summary\n",
                "    for cluster in range(best_k):\n",
                "        cluster_whales = features_df[features_df['cluster'] == cluster]['address'].tolist()\n",
                "        cluster_data = positions_df[positions_df['address'].isin(cluster_whales)]\n",
                "        \n",
                "        print(f\"\\nCluster {cluster+1} Summary:\")\n",
                "        print(f\"Number of whales: {len(cluster_whales)}\")\n",
                "        print(f\"Total position value: ${cluster_data['position_value'].sum():,.0f}\")\n",
                "        \n",
                "        # Top coins in this cluster\n",
                "        coin_values = cluster_data.groupby('coin')['position_value'].sum().sort_values(ascending=False)\n",
                "        print(f\"Top 3 coins: {', '.join(coin_values.index[:3].tolist())}\")\n",
                "        \n",
                "        # Long/short bias\n",
                "        long_pct = cluster_data[cluster_data['is_long']]['position_value'].sum() / cluster_data['position_value'].sum() * 100\n",
                "        print(f\"Long bias: {long_pct:.1f}%\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 5. Custom Whale Query Tool"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "def query_whales(min_value=100000, coins=None, is_long=None, min_positions=1):\n",
                "    \"\"\"Query whales based on criteria\"\"\"\n",
                "    # Start with all positions\n",
                "    filtered = positions_df.copy()\n",
                "    \n",
                "    # Apply filters\n",
                "    if coins:\n",
                "        filtered = filtered[filtered['coin'].isin(coins)]\n",
                "    \n",
                "    if is_long is not None:\n",
                "        filtered = filtered[filtered['is_long'] == is_long]\n",
                "    \n",
                "    # Find whales with sufficient position value\n",
                "    whale_values = filtered.groupby('address')['position_value'].sum()\n",
                "    qualifying_whales = whale_values[whale_values >= min_value].index.tolist()\n",
                "    \n",
                "    # Check position count\n",
                "    position_counts = filtered[filtered['address'].isin(qualifying_whales)]['address'].value_counts()\n",
                "    active_whales = position_counts[position_counts >= min_positions].index.tolist()\n",
                "    \n",
                "    # Get final whale list\n",
                "    final_whales = []\n",
                "    for whale in active_whales:\n",
                "        whale_data = filtered[filtered['address'] == whale]\n",
                "        \n",
                "        final_whales.append({\n",
                "            'address': whale,\n",
                "            'short_address': f\"{whale[:6]}...{whale[-4:]}\",\n",
                "            'total_value': whale_data['position_value'].sum(),\n",
                "            'position_count': len(whale_data),\n",
                "            'coin_count': whale_data['coin'].nunique(),\n",
                "            'main_coin': whale_data.groupby('coin')['position_value'].sum().idxmax(),\n",
                "            'long_pct': whale_data[whale_data['is_long']]['position_value'].sum() / whale_data['position_value'].sum() * 100\n",
                "        })\n",
                "    \n",
                "    # Create DataFrame and sort\n",
                "    result_df = pd.DataFrame(final_whales)\n",
                "    if not result_df.empty:\n",
                "        result_df = result_df.sort_values('total_value', ascending=False)\n",
                "    \n",
                "    return result_df\n",
                "\n",
                "# Interactive query example: Top BTC long positions\n",
                "btc_longs = query_whales(min_value=500000, coins=['BTC'], is_long=True)\n",
                "if not btc_longs.empty:\n",
                "    print(f\"Found {len(btc_longs)} whales with significant BTC long positions\")\n",
                "    display(btc_longs.style.format({\n",
                "        'total_value': '${:,.0f}',\n",
                "        'long_pct': '{:.1f}%'\n",
                "    }))\n",
                "else:\n",
                "    print(\"No matching whales found.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 6. Export Custom Reports"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "def export_filtered_data(min_value=100000, coins=None, is_long=None, filename=\"custom_whale_report.csv\"):\n",
                "    \"\"\"Export filtered whale data to CSV\"\"\"\n",
                "    # Query whales\n",
                "    whales_df = query_whales(min_value=min_value, coins=coins, is_long=is_long)\n",
                "    \n",
                "    if whales_df.empty:\n",
                "        print(\"No matching whales found.\")\n",
                "        return\n",
                "    \n",
                "    # Export to CSV\n",
                "    export_path = os.path.join(DATA_DIR, filename)\n",
                "    whales_df.to_csv(export_path, index=False)\n",
                "    print(f\"✅ Exported {len(whales_df)} whale records to {export_path}\")\n",
                "    \n",
                "    return export_path\n",
                "\n",
                "# Example: Export whales with large ETH positions (both long and short)\n",
                "eth_export = export_filtered_data(min_value=250000, coins=['ETH'], filename=\"eth_whales.csv\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook to a file
with open('whale_analysis.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Notebook created successfully: whale_analysis.ipynb") 